name: pika-datasets
channels:
  - conda-forge
  - defaults
dependencies:
  - click
  - tqdm
  - gdal
  - requests
  - networkx
  - shapely
  - lxml
  - geopandas
  - rasterio
  - geojson
  - tippecanoe
  - pyproj
  - scikit-geometry
  - rtree
  - scipy
  - rclone
  - jellyfish
  - pip
  - pip:
      - rio-rgbify
      - simplification
      - geopolygonize
