name: pika-datasets
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - click
  - tqdm
  - gdal
  - requests
  - networkx
  - shapely
  - lxml
  - geopandas
  - rasterio
  - geojson
  - tippecanoe
  - pyproj
  - rtree
  - scipy
  - rclone
  - jellyfish
  - osmium-tool
  - pip
  - pip:
      - rio-rgbify
      - simplification
      - geopolygonize
      - osmium
